plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':domain')
    implementation project(':application')
    implementation project(':api')
    implementation project(':infrastructure')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.testcontainers:junit-jupiter:1.20.6'
    testImplementation 'org.testcontainers:mariadb:1.20.6'
    testImplementation 'org.flywaydb:flyway-core'
    testImplementation 'org.flywaydb:flyway-mysql'
    testImplementation 'org.apache.httpcomponents.client5:httpclient5'
}

test { useJUnitPlatform() }
