plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':domain')
    implementation project(':application')
    implementation project(':api')
    implementation project(':infrastructure')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test { useJUnitPlatform() }
