spring:
  application:
    name: backup-poc
  threads:
    virtual:
      enabled: true

server:
  port: 8080
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1
  servlet:
    multipart:
      enabled: false

backup:
  storage:
    incoming-root: ${HOME}/backup-poc/incoming
  tus:
    max-upload-size: 10737418240   # 10GB

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    me.desair.tus: DEBUG
    com.intocns.backupfileserver: DEBUG
